In [39]:
#Import libraries
import pandas as pd
import numpy as np
np.nan is np.NaN is np.NAN
import os

# Importing Immo Data

In [40]:
path = r'C:\Users\s.wienecke\Documents\Fortbildung\Letztes Modul'

In [41]:
df = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'immo_data.csv'), index_col = False)

# Data Profile

In [42]:
pd.set_option('display.max_columns', None)

In [43]:
df.head(10)

,regio1,serviceCharge,heatingType,telekomTvOffer,telekomHybridUploadSpeed,newlyConst,balcony,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,noParkSpaces,firingTypes,hasKitchen,geo_bln,cellar,yearConstructedRange,baseRent,houseNumber,livingSpace,geo_krs,condition,interiorQual,petsAllowed,street,streetPlain,lift,baseRentRange,typeOfFlat,geo_plz,noRooms,thermalChar,floor,numberOfFloors,noRoomsRange,garden,livingSpaceRange,regio2,regio3,description,facilities,heatingCosts,energyEfficiencyClass,lastRefurbish,electricityBasePrice,electricityKwhPrice,date
0,Nordrhein_Westfalen,245.00,central_heating,ONE_YEAR_FREE,NaN,False,False,6,4.62,10.0,840.00,1965.0,96107057,1.0,oil,False,Nordrhein_Westfalen,True,2.0,595.00,244,86.00,Dortmund,well_kept,normal,NaN,Sch&uuml;ruferstra&szlig;e,Schüruferstraße,False,4,ground_floor,44269,4.0,181.4,1.0,3.0,4,True,4,Dortmund,Schüren,Die ebenerdig zu erreichende Erdgeschosswohnun...,Die Wohnung ist mit Laminat ausgelegt. Das Bad...,NaN,NaN,NaN,NaN,NaN,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,ONE_YEAR_FREE,NaN,False,True,8,3.47,10.0,NaN,1871.0,111378734,2.0,gas,False,Rheinland_Pfalz,False,1.0,800.00,NaN,89.00,Rhein_Pfalz_Kreis,refurbished,normal,no,no_information,NaN,False,5,ground_floor,67459,3.0,NaN,NaN,NaN,3,False,4,Rhein_Pfalz_Kreis,Böhl_Iggelheim,Alles neu macht der Mai – so kann es auch für ...,NaN,NaN,NaN,2019.0,NaN,NaN,May19
2,Sachsen,255.00,floor_heating,ONE_YEAR_FREE,10.0,True,True,8,2.72,2.4,1300.00,2019.0,113147523,1.0,NaN,False,Sachsen,True,9.0,965.00,4,83.80,Dresden,first_time_use,sophisticated,NaN,Turnerweg,Turnerweg,True,6,apartment,1097,3.0,NaN,3.0,4.0,3,False,4,Dresden,Äußere_Neustadt_Antonstadt,Der Neubau entsteht im Herzen der Dresdner Neu...,"* 9 m² Balkon\n* Bad mit bodengleicher Dusche,...",NaN,NaN,NaN,NaN,NaN,Oct19
3,Sachsen,58.15,district_heating,ONE_YEAR_FREE,NaN,False,True,9,1.53,40.0,NaN,1964.0,108890903,NaN,district_heating,False,Sachsen,False,2.0,343.00,35,58.15,Mittelsachsen_Kreis,NaN,NaN,NaN,Gl&uuml;ck-Auf-Stra&szlig;e,Glück-Auf-Straße,False,2,other,9599,3.0,86.0,3.0,NaN,3,False,2,Mittelsachsen_Kreis,Freiberg,Abseits von Lärm und Abgasen in Ihre neue Wohn...,NaN,87.23,NaN,NaN,NaN,NaN,May19
4,Bremen,138.00,self_contained_central_heating,NaN,NaN,False,True,19,2.46,NaN,903.00,1950.0,114751222,NaN,gas,False,Bremen,False,1.0,765.00,10,84.97,Bremen,refurbished,NaN,NaN,Hermann-Henrich-Meier-Allee,Hermann-Henrich-Meier-Allee,False,5,apartment,28213,3.0,188.9,1.0,NaN,3,False,4,Bremen,Neu_Schwachhausen,Es handelt sich hier um ein saniertes Mehrfami...,Diese Wohnung wurde neu saniert und ist wie fo...,NaN,NaN,NaN,NaN,NaN,Feb20
5,Schleswig_Holstein,142.00,gas_heating,NONE,NaN,False,True,5,4.48,2.4,NaN,1999.0,115531145,NaN,gas,True,Schleswig_Holstein,False,5.0,315.20,1e,53.43,Schleswig_Flensburg_Kreis,well_kept,NaN,no,Hardeseiche,Hardeseiche,False,2,apartment,24891,2.0,165.0,NaN,NaN,2,False,2,Schleswig_Flensburg_Kreis,Struxdorf,NaN,"helle ebenerdige 2 Zi. Wohnung mit Terrasse, h...",NaN,NaN,NaN,NaN,NaN,Feb20
6,Sachsen,70.00,self_contained_central_heating,ONE_YEAR_FREE,10.0,False,False,9,1.01,2.4,380.00,NaN,114391930,NaN,NaN,False,Sachsen,True,NaN,310.00,14,62.00,Mittelsachsen_Kreis,fully_renovated,NaN,NaN,Am Bahnhof,Am_Bahnhof,False,2,NaN,9599,2.0,NaN,1.0,4.0,2,True,3,Mittelsachsen_Kreis,Freiberg,Am Bahnhof 14 in Freiberg\nHeizkosten und Warm...,NaN,NaN,NaN,NaN,NaN,NaN,Feb20
7,Bremen,88.00,central_heating,ONE_YEAR_FREE,10.0,False,True,5,1.89,2.4,584.25,1959.0,115270775,NaN,gas:electricity,False,Bremen,True,2.0,452.25,35,60.30,Bremen,NaN,NaN,NaN,Lesumer Heerstr.,Lesumer_Heerstr.,False,3,ground_floor,28717,3.0,63.0,NaN,NaN,3,False,2,Bremen,St._Magnus,+ Komfortabler Bodenbelag: Die Wohnung ist zus...,Rollläden; Warmwasserbereiter; Kellerraum; Gas...,44.00,B,NaN,NaN,NaN,Feb20
8,Baden_Württemberg,110.00,oil_heating,ONE_YEAR_FREE,NaN,False,False,5,3.77,40.0,690.00,1970.0,106416361,1.0,oil,True,Baden_Württemberg,True,2.0,580.00,NaN,53.00,Emmendingen_Kreis,well_kept,sophisticated,no,no_information,NaN,False,4,roof_storey,79211,2.0,138.0,2.0,2.0,2,False,2,Emmendingen_Kreis,Denzlingen,"Diese ansprechende, lichtdurchflutete DG-Wohnu...","Parkett, Einbauküche, kein Balkon",NaN,E,NaN,NaN,NaN,Feb20
9,Nordrhein_Westfalen,95.00,self_contained_central_heating,ONE_YEAR_FREE,NaN,False,False,7,1.92,40.0,NaN,1953.0,91383597,NaN,gas,False,Nordrhein_Westfalen,True,2.0,300.00,30,60.00,Gelsenkirchen,well_kept,normal,negotiable,H&uuml;ttenstr.,Hüttenstr.,False,1,apartment,45888,2.5,207.7,2.0,5.0,2,False,2,Gelsenkirchen,Bulmke_Hüllen,Sie sind auf der Suche nach einer gepflegten u...,In Ihrem neuen Zuhause können Sie nach wenigen...,NaN,NaN,NaN,NaN,NaN,Oct19

In [44]:
df.shape

(268850, 49)

In [45]:
df.dtypes

regio1                       object
serviceCharge               float64
heatingType                  object
telekomTvOffer               object
telekomHybridUploadSpeed    float64
newlyConst                     bool
balcony                        bool
picturecount                  int64
pricetrend                  float64
telekomUploadSpeed          float64
totalRent                   float64
yearConstructed             float64
scoutId                       int64
noParkSpaces                float64
firingTypes                  object
hasKitchen                     bool
geo_bln                      object
cellar                         bool
yearConstructedRange        float64
baseRent                    float64
houseNumber                  object
livingSpace                 float64
geo_krs                      object
condition                    object
interiorQual                 object
petsAllowed                  object
street                       object
streetPlain                  object
lift                           bool
baseRentRange                 int64
typeOfFlat                   object
geo_plz                       int64
noRooms                     float64
thermalChar                 float64
floor                       float64
numberOfFloors              float64
noRoomsRange                  int64
garden                         bool
livingSpaceRange              int64
regio2                       object
regio3                       object
description                  object
facilities                   object
heatingCosts                float64
energyEfficiencyClass        object
lastRefurbish               float64
electricityBasePrice        float64
electricityKwhPrice         float64
date                         object
dtype: object

In [46]:
df.describe()

,serviceCharge,telekomHybridUploadSpeed,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,noParkSpaces,yearConstructedRange,baseRent,livingSpace,baseRentRange,geo_plz,noRooms,thermalChar,floor,numberOfFloors,noRoomsRange,livingSpaceRange,heatingCosts,lastRefurbish,electricityBasePrice,electricityKwhPrice
count,261941.000000,45020.0,268850.000000,267018.000000,235492.000000,2.283330e+05,211805.000000,2.688500e+05,93052.000000,211805.000000,2.688500e+05,268850.000000,268850.000000,268850.000000,268850.000000,162344.000000,217541.000000,171118.000000,268850.000000,268850.000000,85518.000000,80711.000000,46846.000000,46846.000000
mean,151.206113,10.0,9.791958,3.389001,28.804928,9.013315e+02,1966.400590,1.069697e+08,1.327634,3.714544,6.941294e+02,74.355548,3.765256,37283.022235,2.641261,114.749533,2.122405,3.572319,2.571542,3.070790,76.990866,2013.904536,89.113612,0.199769
std,308.295790,0.0,6.408399,1.964874,16.337151,3.323833e+04,46.992207,1.250093e+07,8.361403,2.738134,1.953602e+04,254.759208,2.214357,27798.037296,2.633440,61.653663,3.634934,6.375496,0.937594,1.407127,147.716278,10.963125,5.395805,0.009667
min,0.000000,10.0,0.000000,-12.330000,1.000000,0.000000e+00,1000.000000,2.887174e+07,0.000000,1.000000,0.000000e+00,0.000000,1.000000,852.000000,1.000000,0.100000,-1.000000,0.000000,1.000000,1.000000,0.000000,1015.000000,71.430000,0.170500
25%,95.000000,10.0,6.000000,2.000000,10.000000,4.698000e+02,1950.000000,1.066910e+08,1.000000,1.000000,3.380000e+02,54.000000,2.000000,9128.000000,2.000000,79.000000,1.000000,2.000000,2.000000,2.000000,54.000000,2012.000000,90.760000,0.191500
50%,135.000000,10.0,9.000000,3.390000,40.000000,6.500000e+02,1973.000000,1.111584e+08,1.000000,3.000000,4.900000e+02,67.320000,3.000000,38667.000000,3.000000,107.000000,2.000000,3.000000,3.000000,3.000000,70.000000,2017.000000,90.760000,0.198500
75%,190.000000,10.0,13.000000,4.570000,40.000000,9.850000e+02,1996.000000,1.137688e+08,1.000000,5.000000,7.990000e+02,87.000000,5.000000,57072.000000,3.000000,140.300000,3.000000,4.000000,3.000000,4.000000,90.000000,2019.000000,90.760000,0.205500
max,146118.000000,10.0,121.000000,14.920000,100.000000,1.575154e+07,2090.000000,1.157117e+08,2241.000000,9.000000,9.999999e+06,111111.000000,9.000000,99998.000000,999.990000,1996.000000,999.000000,999.000000,5.000000,7.000000,12613.000000,2919.000000,90.760000,0.227600

# Dropping columns

In [47]:
# df2 = creating a new dataframe for the clean version with e.g. dropped columns
df2 = df.drop(columns = ['geo_bln', 'houseNumber','geo_krs','street','streetPlain', 'description', 'facilities'
])

In [48]:
df2.head()

,regio1,serviceCharge,heatingType,telekomTvOffer,telekomHybridUploadSpeed,newlyConst,balcony,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,noParkSpaces,firingTypes,hasKitchen,cellar,yearConstructedRange,baseRent,livingSpace,condition,interiorQual,petsAllowed,lift,baseRentRange,typeOfFlat,geo_plz,noRooms,thermalChar,floor,numberOfFloors,noRoomsRange,garden,livingSpaceRange,regio2,regio3,heatingCosts,energyEfficiencyClass,lastRefurbish,electricityBasePrice,electricityKwhPrice,date
0,Nordrhein_Westfalen,245.00,central_heating,ONE_YEAR_FREE,NaN,False,False,6,4.62,10.0,840.0,1965.0,96107057,1.0,oil,False,True,2.0,595.0,86.00,well_kept,normal,NaN,False,4,ground_floor,44269,4.0,181.4,1.0,3.0,4,True,4,Dortmund,Schüren,NaN,NaN,NaN,NaN,NaN,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,ONE_YEAR_FREE,NaN,False,True,8,3.47,10.0,NaN,1871.0,111378734,2.0,gas,False,False,1.0,800.0,89.00,refurbished,normal,no,False,5,ground_floor,67459,3.0,NaN,NaN,NaN,3,False,4,Rhein_Pfalz_Kreis,Böhl_Iggelheim,NaN,NaN,2019.0,NaN,NaN,May19
2,Sachsen,255.00,floor_heating,ONE_YEAR_FREE,10.0,True,True,8,2.72,2.4,1300.0,2019.0,113147523,1.0,NaN,False,True,9.0,965.0,83.80,first_time_use,sophisticated,NaN,True,6,apartment,1097,3.0,NaN,3.0,4.0,3,False,4,Dresden,Äußere_Neustadt_Antonstadt,NaN,NaN,NaN,NaN,NaN,Oct19
3,Sachsen,58.15,district_heating,ONE_YEAR_FREE,NaN,False,True,9,1.53,40.0,NaN,1964.0,108890903,NaN,district_heating,False,False,2.0,343.0,58.15,NaN,NaN,NaN,False,2,other,9599,3.0,86.0,3.0,NaN,3,False,2,Mittelsachsen_Kreis,Freiberg,87.23,NaN,NaN,NaN,NaN,May19
4,Bremen,138.00,self_contained_central_heating,NaN,NaN,False,True,19,2.46,NaN,903.0,1950.0,114751222,NaN,gas,False,False,1.0,765.0,84.97,refurbished,NaN,NaN,False,5,apartment,28213,3.0,188.9,1.0,NaN,3,False,4,Bremen,Neu_Schwachhausen,NaN,NaN,NaN,NaN,NaN,Feb20

In [49]:
# identifying columns which have more than 25% of missing values
df2.loc[:,df2.isna().mean() > 0.25].columns

Index(['telekomHybridUploadSpeed', 'noParkSpaces', 'condition', 'interiorQual',
       'petsAllowed', 'thermalChar', 'numberOfFloors', 'heatingCosts',
       'energyEfficiencyClass', 'lastRefurbish', 'electricityBasePrice',
       'electricityKwhPrice'],
      dtype='object')

In [70]:
# dropping colums
df2 = df2.drop(columns = ['telekomHybridUploadSpeed', 'noParkSpaces', 'condition', 'interiorQual',
       'petsAllowed', 'thermalChar', 'numberOfFloors', 'heatingCosts',
       'energyEfficiencyClass', 'lastRefurbish', 'electricityBasePrice',
       'electricityKwhPrice'])

In [71]:
# showing the number of rows & colums of df2 without dropped columns
df2.shape

(268850, 30)

# Renaming Columns

In [72]:
# renaming colums
df2.rename(columns = {'regio1' : 'state', 'geo_plz' : 'postcode', 'regio2' : 'city/county', 'regio3' : 'city district'}, inplace = True)

In [73]:
df2.head(30)

,state,serviceCharge,heatingType,telekomTvOffer,newlyConst,balcony,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,firingTypes,hasKitchen,cellar,yearConstructedRange,baseRent,livingSpace,lift,baseRentRange,typeOfFlat,postcode,noRooms,floor,noRoomsRange,garden,livingSpaceRange,city/county,city district,date
0,Nordrhein_Westfalen,245.00,central_heating,ONE_YEAR_FREE,False,False,6,4.62,10.000000,840.000000,1965.00000,96107057,oil,False,True,2.000000,595.00,86.00,False,4,ground_floor,44269,4.0,1.000000,4,True,4,Dortmund,Schüren,May19
1,Rheinland_Pfalz,134.00,self_contained_central_heating,ONE_YEAR_FREE,False,True,8,3.47,10.000000,901.331522,1871.00000,111378734,gas,False,False,1.000000,800.00,89.00,False,5,ground_floor,67459,3.0,2.122405,3,False,4,Rhein_Pfalz_Kreis,Böhl_Iggelheim,May19
2,Sachsen,255.00,floor_heating,ONE_YEAR_FREE,True,True,8,2.72,2.400000,1300.000000,2019.00000,113147523,nan,False,True,9.000000,965.00,83.80,True,6,apartment,1097,3.0,3.000000,3,False,4,Dresden,Äußere_Neustadt_Antonstadt,Oct19
3,Sachsen,58.15,district_heating,ONE_YEAR_FREE,False,True,9,1.53,40.000000,901.331522,1964.00000,108890903,district_heating,False,False,2.000000,343.00,58.15,False,2,other,9599,3.0,3.000000,3,False,2,Mittelsachsen_Kreis,Freiberg,May19
4,Bremen,138.00,self_contained_central_heating,nan,False,True,19,2.46,28.804928,903.000000,1950.00000,114751222,gas,False,False,1.000000,765.00,84.97,False,5,apartment,28213,3.0,1.000000,3,False,4,Bremen,Neu_Schwachhausen,Feb20
5,Schleswig_Holstein,142.00,gas_heating,NONE,False,True,5,4.48,2.400000,901.331522,1999.00000,115531145,gas,True,False,5.000000,315.20,53.43,False,2,apartment,24891,2.0,2.122405,2,False,2,Schleswig_Flensburg_Kreis,Struxdorf,Feb20
6,Sachsen,70.00,self_contained_central_heating,ONE_YEAR_FREE,False,False,9,1.01,2.400000,380.000000,1966.40059,114391930,nan,False,True,3.714544,310.00,62.00,False,2,nan,9599,2.0,1.000000,2,True,3,Mittelsachsen_Kreis,Freiberg,Feb20
7,Bremen,88.00,central_heating,ONE_YEAR_FREE,False,True,5,1.89,2.400000,584.250000,1959.00000,115270775,gas:electricity,False,True,2.000000,452.25,60.30,False,3,ground_floor,28717,3.0,2.122405,3,False,2,Bremen,St._Magnus,Feb20
8,Baden_Württemberg,110.00,oil_heating,ONE_YEAR_FREE,False,False,5,3.77,40.000000,690.000000,1970.00000,106416361,oil,True,True,2.000000,580.00,53.00,False,4,roof_storey,79211,2.0,2.000000,2,False,2,Emmendingen_Kreis,Denzlingen,Feb20
9,Nordrhein_Westfalen,95.00,self_contained_central_heating,ONE_YEAR_FREE,False,False,7,1.92,40.000000,901.331522,1953.00000,91383597,gas,False,True,2.000000,300.00,60.00,False,1,apartment,45888,2.5,2.000000,2,False,2,Gelsenkirchen,Bulmke_Hüllen,Oct19
10,Sachsen,88.00,nan,ONE_YEAR_FREE,False,True,11,0.21,40.000000,307.000000,1930.00000,112923517,gas,False,True,1.000000,219.00,40.20,False,1,apartment,9130,2.0,3.000000,2,False,1,Chemnitz,Sonnenberg,Oct19
11,Sachsen,155.00,central_heating,ONE_YEAR_FREE,False,False,9,0.98,2.400000,555.000000,1892.00000,109842225,gas,False,True,1.000000,400.00,80.00,False,2,nan,9669,3.0,1.000000,3,True,3,Mittelsachsen_Kreis,Frankenberg/Sachsen,May19
12,Rheinland_Pfalz,270.00,oil_heating,NONE,False,False,4,2.77,2.400000,920.000000,1912.00000,111251778,nan,False,False,1.000000,650.00,100.00,False,5,ground_floor,76833,4.0,2.122405,4,True,4,Südliche_Weinstraße_Kreis,Frankweiler,May19
13,Nordrhein_Westfalen,200.00,central_heating,ONE_YEAR_FREE,False,False,3,3.45,40.000000,1150.000000,1951.00000,101730329,oil,False,False,2.000000,950.00,123.44,False,6,apartment,59065,4.0,4.000000,4,False,6,Hamm,Mitte,Oct19
14,Nordrhein_Westfalen,215.00,gas_heating,ONE_YEAR_FREE,True,True,12,3.76,2.400000,1320.650000,2018.00000,92798563,gas,False,True,9.000000,972.60,87.00,True,6,ground_floor,44229,3.0,0.000000,3,False,4,Dortmund,Kirchhörde,May19
15,Thüringen,80.00,district_heating,ONE_YEAR_FREE,False,True,5,1.67,2.400000,300.000000,1990.00000,106896167,district_heating,False,True,4.000000,220.00,36.63,False,1,apartment,99427,1.0,4.000000,1,False,1,Weimar,Schöndorf,Sep18
16,Hessen,220.00,oil_heating,ONE_YEAR_FREE,False,True,17,3.85,40.000000,970.000000,1966.40059,93522345,oil,False,True,3.714544,750.00,87.00,False,5,apartment,63452,3.0,2.122405,3,False,4,Main_Kinzig_Kreis,Hanau,Oct19
17,Sachsen,50.00,central_heating,ONE_YEAR_FREE,False,False,12,1.96,40.000000,325.000000,1897.00000,107018003,gas,False,False,1.000000,200.00,50.00,False,1,roof_storey,4720,2.0,3.000000,2,True,2,Mittelsachsen_Kreis,Döbeln,Sep18
18,Nordrhein_Westfalen,121.00,central_heating,ONE_YEAR_FREE,False,True,5,3.12,40.000000,901.331522,1914.00000,111227157,gas,False,True,1.000000,329.00,65.00,False,2,apartment,47166,2.5,2.000000,2,False,3,Duisburg,Obermarxloh,May19
19,Niedersachsen,290.00,district_heating,ONE_YEAR_FREE,False,True,35,2.35,5.000000,1878.480000,2013.00000,113019528,district_heating,False,True,8.000000,1343.48,127.95,True,7,apartment,37073,5.0,1.000000,5,False,6,Göttingen_Kreis,Göttingen,Oct19
20,Schleswig_Holstein,140.00,central_heating,ONE_YEAR_FREE,False,True,15,5.00,10.000000,1450.000000,1978.00000,110416311,gas,False,True,3.000000,1150.00,160.00,False,7,ground_floor,24539,4.0,0.000000,4,True,7,Neumünster,Wittorf,Oct19
21,Baden_Württemberg,0.00,nan,ONE_YEAR_FREE,False,False,13,5.63,40.000000,1190.000000,1966.40059,113836264,nan,False,False,3.714544,1190.00,29.00,False,7,apartment,70376,1.5,3.000000,1,False,1,Stuttgart,Bad_Cannstatt,Oct19
22,Sachsen,346.00,central_heating,ONE_YEAR_FREE,False,True,22,5.34,40.000000,1946.000000,1966.40059,111412293,district_heating,False,False,3.714544,1600.00,140.00,True,8,roof_storey,4229,4.0,0.000000,4,True,6,Leipzig,Lindenau,Oct19
23,Bayern,180.00,central_heating,ONE_YEAR_FREE,False,False,18,4.47,10.000000,2030.000000,1871.00000,113626688,district_heating,True,True,1.000000,1850.00,81.00,False,8,apartment,80331,2.0,4.000000,2,False,4,München,Altstadt,Oct19
24,Hamburg,140.00,central_heating,ONE_YEAR_FREE,False,True,9,6.30,40.000000,760.000000,1953.00000,111337159,district_heating,False,True,2.000000,620.00,55.89,False,5,apartment,22111,3.0,2.000000,3,False,2,Hamburg,Horn,May19
25,Niedersachsen,80.00,district_heating,ONE_YEAR_FREE,False,False,7,0.59,40.000000,396.000000,1890.00000,115506913,district_heating,False,False,1.000000,316.00,31.00,False,2,roof_storey,38118,1.5,2.122405,1,False,1,Braunschweig,Westliches_Ringgebiet,Feb20
26,Baden_Württemberg,20.00,nan,ONE_YEAR_FREE,False,False,7,4.65,10.000000,355.000000,1902.00000,115403430,electricity,False,False,1.000000,335.00,12.00,False,2,other,72622,1.0,2.122405,1,False,1,Esslingen_Kreis,Nürtingen,Feb20
27,Sachsen_Anhalt,147.32,district_heating,ONE_YEAR_FREE,False,True,14,1.08,40.000000,447.620000,1977.00000,114132653,district_heating,False,True,3.000000,300.30,56.66,True,1,apartment,39128,3.0,6.000000,3,False,2,Magdeburg,Kannenstieg,Feb20
28,Bayern,0.00,nan,ONE_YEAR_FREE,False,True,25,7.53,40.000000,2400.000000,1956.00000,111398027,gas,False,False,2.000000,2400.00,61.00,True,9,nan,80804,3.0,1.000000,3,False,3,München,Schwabing_West,May19
29,Mecklenburg_Vorpommern,104.02,district_heating,ONE_YEAR_FREE,True,True,13,3.72,40.000000,624.100000,2018.00000,111018701,district_heating,False,True,9.000000,520.08,47.28,True,4,raised_ground_floor,19055,2.0,2.122405,2,False,2,Schwerin,Paulsstadt,May19

# Identifying Missing Values

In [74]:
#showing all columns with the number of missing values
df2.isna().sum()

state                   0
serviceCharge           0
heatingType             0
telekomTvOffer          0
newlyConst              0
balcony                 0
picturecount            0
pricetrend              0
telekomUploadSpeed      0
totalRent               0
yearConstructed         0
scoutId                 0
firingTypes             0
hasKitchen              0
cellar                  0
yearConstructedRange    0
baseRent                0
livingSpace             0
lift                    0
baseRentRange           0
typeOfFlat              0
postcode                0
noRooms                 0
floor                   0
noRoomsRange            0
garden                  0
livingSpaceRange        0
city/county             0
city district           0
date                    0
dtype: int64

In [75]:
#showing total record count of missing values
df2.isnull().sum().sum()

0

In [78]:
df2.shape

(268850, 30)

# Checking Mixed-type Columns

In [66]:
for col in df2.columns.tolist():
  weird = (df2[[col]].applymap(type) != df2[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df2[weird]) > 0:
    print (col)

heatingType
telekomTvOffer
firingTypes
condition
interiorQual
petsAllowed
typeOfFlat
energyEfficiencyClass

In [67]:
#changing types of these columns
df2['heatingType'] = df2['heatingType'].astype('str')
df2['telekomTvOffer'] = df2['telekomTvOffer'].astype('str')
df2['firingTypes'] = df2['firingTypes'].astype('str')
df2['condition'] = df2['condition'].astype('str')
df2['interiorQual'] = df2['interiorQual'].astype('str')
df2['petsAllowed'] = df2['petsAllowed'].astype('str')
df2['typeOfFlat'] = df2['typeOfFlat'].astype('str')
df2['energyEfficiencyClass'] = df2['energyEfficiencyClass'].astype('str')

# Checking for Duplicates

In [68]:
#checking for duplicates
df_dups = df2[df2.duplicated()]

In [69]:
df_dups

Empty DataFrame
Columns: [state, serviceCharge, heatingType, telekomTvOffer, telekomHybridUploadSpeed, newlyConst, balcony, picturecount, pricetrend, telekomUploadSpeed, totalRent, yearConstructed, scoutId, noParkSpaces, firingTypes, hasKitchen, cellar, yearConstructedRange, baseRent, livingSpace, condition, interiorQual, petsAllowed, lift, baseRentRange, typeOfFlat, postcode, noRooms, thermalChar, floor, numberOfFloors, noRoomsRange, garden, livingSpaceRange, city/county, city district, heatingCosts, energyEfficiencyClass, lastRefurbish, electricityBasePrice, electricityKwhPrice, date]
Index: []

In [81]:
df2.describe()

,serviceCharge,picturecount,pricetrend,telekomUploadSpeed,totalRent,yearConstructed,scoutId,yearConstructedRange,baseRent,livingSpace,baseRentRange,postcode,noRooms,floor,noRoomsRange,livingSpaceRange
count,268850.000000,268850.000000,268850.000000,268850.000000,2.688500e+05,268850.000000,2.688500e+05,268850.000000,2.688500e+05,268850.000000,268850.000000,268850.000000,268850.000000,268850.000000,268850.000000,268850.000000
mean,151.206113,9.791958,3.389001,28.804928,9.013315e+02,1966.400590,1.069697e+08,3.714544,6.941294e+02,74.355548,3.765256,37283.022235,2.641261,2.122405,2.571542,3.070790
std,304.308647,6.408399,1.958168,15.290063,3.063151e+04,41.709858,1.250093e+07,2.430343,1.953602e+04,254.759208,2.214357,27798.037296,2.633440,3.269730,0.937594,1.407127
min,0.000000,0.000000,-12.330000,1.000000,0.000000e+00,1000.000000,2.887174e+07,1.000000,0.000000e+00,0.000000,1.000000,852.000000,1.000000,-1.000000,1.000000,1.000000
25%,96.000000,6.000000,2.000000,10.000000,4.950000e+02,1958.000000,1.066910e+08,2.000000,3.380000e+02,54.000000,2.000000,9128.000000,2.000000,1.000000,2.000000,2.000000
50%,140.000000,9.000000,3.389001,40.000000,7.410000e+02,1966.400590,1.111584e+08,3.714544,4.900000e+02,67.320000,3.000000,38667.000000,3.000000,2.000000,3.000000,3.000000
75%,185.000000,13.000000,4.560000,40.000000,9.013315e+02,1992.000000,1.137688e+08,5.000000,7.990000e+02,87.000000,5.000000,57072.000000,3.000000,3.000000,3.000000,4.000000
max,146118.000000,121.000000,14.920000,100.000000,1.575154e+07,2090.000000,1.157117e+08,9.000000,9.999999e+06,111111.000000,9.000000,99998.000000,999.990000,999.000000,5.000000,7.000000

# Frequency Tables

In [86]:
df2['yearConstructedRange'].value_counts()

350.00     3810
450.00     3558
300.00     3152
400.00     2985
650.00     2905
           ...
380.59        1
496.19        1
1236.80       1
807.66        1
738.50        1
Name: baseRent, Length: 26659, dtype: int64

In [87]:
df2['baseRent'].value_counts()

350.00     3810
450.00     3558
300.00     3152
400.00     2985
650.00     2905
           ...
380.59        1
496.19        1
1236.80       1
807.66        1
738.50        1
Name: baseRent, Length: 26659, dtype: int64

In [88]:
df2['livingSpace'].value_counts()

60.00     5189
70.00     4154
80.00     4031
65.00     3808
75.00     3692
          ...
155.74       1
152.86       1
102.07       1
151.20       1
145.55       1
Name: livingSpace, Length: 13005, dtype: int64

In [89]:
df2['noRooms'].value_counts()

3.0      92089
2.0      89038
1.0      27805
4.0      27776
2.5       9583
         ...
14.0         1
560.0        1
50.0         1
2.9          1
1.3          1
Name: noRooms, Length: 64, dtype: int64

In [90]:
df2['picturecount'].value_counts()

8      21930
7      21429
9      21421
10     19819
6      18848
       ...
100        1
101        1
107        1
109        1
112        1
Name: picturecount, Length: 95, dtype: int64

In [91]:
df2['pricetrend'].value_counts()

 0.000000     11082
 3.330000      2211
 3.230000      2042
 3.850000      1884
 3.389001      1832
              ...
-2.530000         1
 14.920000        1
-2.520000         1
 12.870000        1
-0.450000         1
Name: pricetrend, Length: 1235, dtype: int64

In [93]:
df2['baseRentRange'].value_counts()

2    54546
1    48225
5    38000
3    37138
7    27495
4    25808
6    24210
8     8251
9     5177
Name: baseRentRange, dtype: int64

# Export

In [94]:
# export df2 to folder Prepared Data
df2.to_csv(os.path.join(path, '02 Data','Prepared Data', 'immo_data_clean.csv'))